import { createClient } from '@supabase/supabase-js';

const supabaseUrl = process.env.eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx2Z2JnZmhncGdjaHRza2ZpcXR2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzg1MjgyMDIsImV4cCI6MjA5NDEwNDIwMn0.uqjKJ9btLJzW8jJSVKFeY9S7r6iOl5sJ16MmmQ46Jdk;
const supabaseAnonKey = process.env.eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx2Z2JnZmhncGdjaHRza2ZpcXR2Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3ODUyODIwMiwiZXhwIjoyMDk0MTA0MjAyfQ.SS2WQkMyyrD-qsYE1F-FRKEXdNOvmSy33hzjvbcuwoQ;

export const supabase = createClient(supabaseUrl, supabaseAnonKey);